FROM node:20-alpine

WORKDIR /app

# 1. Copy the shared dependency folder (if API Gateway also uses it)
COPY logger ./logger

# 2. Copy the api-gateway package files
COPY api-gateway/package*.json ./api-gateway/

# 3. Switch to service folder
WORKDIR /app/api-gateway

# 4. Install dependencies (using --install-links for local dependencies)
RUN npm install --install-links

# 5. Copy source code
COPY api-gateway/ .

EXPOSE 4000

CMD ["node", "src/server.js"]
